const dropdownData = {
    style: {
        "realistic": "Реалистичный (Photorealistic)",
        "animation-3d": "3D Анимация (Pixar/Disney)",
        "anime": "Аниме (Японская анимация)",
        "abstract": "Абстрактный",
        "documentary": "Документальный",
        "stop-motion": "Стоп-моушн",
        "surreal": "Сюрреалистичный",
        "fantasy": "Фэнтези (Высокое)",
        "futuristic": "Футуристический (Sci-Fi)",
        "oil-painting": "Масляная живопись",
        "watercolor": "Акварель",
        "low-poly": "Low Poly (3D)",
        "voxel": "Voxel (Minecraft Style)",
        "pixel-art": "Пиксель-арт (8-bit)",
        "comic-book": "Комикс (Стиль Marvel/DC)",
        "noir": "Нуар (Черно-белый, Драматический)",
        "steampunk": "Стимпанк",
        "cyberpunk": "Киберпанк",
        "minimalist": "Минималистичный",
        "hyperrealism": "Гиперреализм",
        "cinematic": "Кинематографический",
        "vintage": "Винтажный (50s/60s)",
        "glitch-art": "Глитч-арт",
        "grunge": "Гранж",
        "sketch": "Карандашный набросок",
        "pop-art": "Поп-арт (Стиль Энди Уорхола)",
        "impressionism": "Импрессионизм",
        "expressionism": "Экспрессионизм",
        "photogrammetry": "Фотограмметрия",
        "tilt-shift": "Тилт-шифт (Миниатюра)",
        "claymation": "Пластилиновая анимация",
        "rotoscoping": "Ротоскопирование"
    },
    intensity: {
        "slightly": "Slightly",
        "moderately": "Moderately",
        "extremely": "Extremely"
    },
    quality: {
        "8k": "8K",
        "4k": "4K",
        "hyperrealism": "Гиперреализм",
        "photorealistic": "Фотореализм",
        "unreal-engine-5": "Unreal Engine 5",
        "octane-render": "Octane Render",
        "v-ray": "V-Ray",
        "ray-tracing": "Ray Tracing",
        "60fps": "60fps",
        "120fps": "120fps",
        "hdr": "HDR",
        "subsurface-scattering": "Subsurface Scattering"
    },
    camera: {
        "medium-shot": "Средний план (Medium Shot)",
        "wide-shot": "Широкий план (Wide Shot)",
        "close-up": "Крупный план (Close-Up)",
        "extreme-close-up": "Экстремально крупный план",
        "long-shot": "Дальний план (Long Shot)",
        "establishing-shot": "Установочный план (Establishing Shot)",
        "dutch-angle": "Голландский угол (Dutch Angle)",
        "low-angle": "Нижний ракурс (Low Angle)",
        "high-angle": "Верхний ракурс (High Angle)",
        "overhead-shot": "Съемка сверху (Overhead/Drone)",
        "tracking": "Следящая камера (Tracking Shot)",
        "dolly-zoom": "Транстрав (Dolly Zoom/Vertigo Effect)",
        "pan-left": "Панорамирование влево",
        "pan-right": "Панорамирование вправо",
        "tilt-up": "Наклон вверх",
        "tilt-down": "Наклон вниз",
        "crane-shot": "Съемка с крана (Crane Shot)",
        "handheld": "Ручная камера (Handheld, Дрожание)",
        "steadicam": "Стедикам (Плавное движение)",
        "point-of-view": "От первого лица (POV)",
        "reverse-shot": "Обратный кадр",
        "arc-shot": "Вращение вокруг объекта (Arc Shot)",
        "zoom-in": "Быстрое приближение (Zoom In)",
        "zoom-out": "Быстрое отдаление (Zoom Out)",
        "slow-motion": "Замедленная съемка (Slow Motion)",
        "time-lapse": "Таймлапс (Ускоренная съемка)",
        "bullet-time": "Эффект 'Матрицы' (Bullet Time)",
        "macro-shot": "Макро-съемка",
        "micro-shot": "Микро-съемка (Под микроскопом)",
        "gimbal-shot": "Съемка с гимбала (Идеально плавно)",
        "whip-pan": "Резкий переход (Whip Pan)",
        "rack-focus": "Перевод фокуса (Rack Focus)"
    },
    lighting: {
        "natural": "Естественное (Natural Light)",
        "cinematic": "Кинематографическое (Dramatic)",
        "neon": "Неоновое (Neon Glow)",
        "backlight": "Контровое (Backlight)",
        "soft": "Мягкое (Soft Lighting)",
        "hard": "Жесткое (Hard Lighting, Резкие тени)",
        "low-key": "Низкий ключ (Low-Key, Много теней)",
        "high-key": "Высокий ключ (High-Key, Яркое, Без теней)",
        "volumetric": "Объемный свет (Volumetric Lighting/God Rays)",
        "rim-light": "Контурный свет (Rim Light)",
        "studio-light": "Студийное (Studio Lighting)",
        "candlelight": "Свечи (Теплое, Мерцающее)",
        "fluorescent": "Флуоресцентное (Холодное, Лампы)",
        "strobe": "Стробоскоп (Strobe Light)",
        "magic-glow": "Волшебное свечение (Magic Glow)",
        "sunset": "Закатное (Golden Hour)",
        "moonlight": "Лунное (Холодное, Синее)",
        "underwater": "Подводное (Зеленоватое)",
        "firelight": "Свет костра (Оранжевое)",
        "street-lamp": "Уличный фонарь (Желтое)",
        "spotlight": "Прожектор (Spotlight)",
        "fill-light": "Заполняющий свет (Fill Light)",
        "practical-light": "Практический свет (Лампы в кадре)",
        "ambient-occlusion": "Ambient Occlusion (Мягкие тени)",
        "ray-tracing": "Ray Tracing (Реалистичные отражения)",
        "chromatic-aberration": "Хроматическая аберрация",
        "flare": "Блик (Lens Flare)",
        "two-tone": "Двухцветное (Two-Tone Lighting)",
        "dramatic": "Драматическое (Chiaroscuro)",
        "silhouetted": "Силуэтное (Silhouetted)",
        "foggy": "Туманное (Foggy)",
        "rainy": "Дождливое (Wet Surfaces)"
    },
    mood: {
        "epic": "Эпическое (Epic)",
        "joyful": "Радостное (Joyful)",
        "tense": "Напряженное (Tense)",
        "calm": "Спокойное (Calm)",
        "nostalgic": "Ностальгическое (Nostalgic)",
        "magical": "Волшебное (Magical)",
        "dystopian": "Дистопическое (Dystopian)",
        "whimsical": "Причудливое (Whimsical)",
        "melancholic": "Меланхоличное (Melancholic)",
        "ominous": "Зловещее (Ominous)",
        "ethereal": "Эфирное (Ethereal)",
        "surreal": "Сюрреалистическое (Surreal)",
        "romantic": "Романтическое (Romantic)",
        "horror": "Ужас (Horror)",
        "action": "Экшн (Action-Packed)",
        "peaceful": "Мирное (Peaceful)",
        "mysterious": "Таинственное (Mysterious)",
        "dramatic": "Драматическое (Dramatic)",
        "gloomy": "Мрачное (Gloomy)",
        "hopeful": "Обнадеживающее (Hopeful)",
        "isolated": "Изолированное (Isolated)",
        "energetic": "Энергичное (Energetic)",
        "dreamlike": "Сонное (Dreamlike)",
        "chaotic": "Хаотичное (Chaotic)",
        "suspenseful": "Напряженное (Suspenseful)",
        "spiritual": "Духовное (Spiritual)",
        "futuristic": "Футуристическое (Futuristic)",
        "historical": "Историческое (Historical)",
        "meditative": "Медитативное (Meditative)",
        "silly": "Глупое (Silly)",
        "intense": "Интенсивное (Intense)",
        "warm": "Теплое (Warm)"
    },
    cinematography: {
        "16:9": "16:9 (Стандарт HD, YouTube)",
        "21:9": "21:9 (Широкоэкранный, Cinematic)",
        "4:3": "4:3 (Винтаж, Ретро)",
        "1:1": "1:1 (Квадрат, Instagram)",
        "9:16": "9:16 (Вертикальный, Reels/TikTok)",
        "2.35:1": "2.35:1 (Ultra Panavision)",
        "1.85:1": "1.85:1 (Американский стандарт)",
        "2.76:1": "2.76:1 (Ben-Hur)",
        "anamorphic": "Анаморфный объектив (Anamorphic Lens)",
        "spherical": "Сферический объектив (Spherical Lens)",
        "fisheye": "Рыбий глаз (Fisheye Lens)",
        "macro": "Макро объектив (Macro Lens)",
        "telephoto": "Телеобъектив (Telephoto Lens)",
        "wide-angle": "Широкоугольный объектив (Wide-Angle Lens)",
        "prime-lens": "Фикс-объектив (Prime Lens)",
        "zoom-lens": "Зум-объектив (Zoom Lens)",
        "vintage-lens": "Винтажный объектив (Vintage Lens)",
        "low-depth": "Малая глубина резкости (Shallow Depth of Field)",
        "deep-depth": "Большая глубина резкости (Deep Depth of Field)",
        "bokeh": "Боке (Bokeh)",
        "film-grain": "Пленка (Film Grain)",
        "digital-clean": "Цифровое (Digital Clean)",
        "vhs-tape": "VHS-пленка (VHS Tape)",
        "super-8": "Super 8mm Film",
        "16mm": "16mm Film",
        "35mm": "35mm Film",
        "imax": "IMAX Format",
        "technicolor": "Техниколор (Technicolor)",
        "sepia": "Сепия (Sepia Tone)",
        "monochrome": "Монохромный (Monochrome)",
        "hdr": "HDR (High Dynamic Range)",
        "sdr": "SDR (Standard Dynamic Range)"
    },
    effect: {
        "none": "Без эффектов",
        "film-grain": "Зернистость пленки (Film Grain)",
        "glitch": "Глитч (Glitch Effect)",
        "depth-of-field": "Глубина резкости (Depth of Field)",
        "smoke-fog": "Дым/Туман (Smoke/Fog)",
        "vhs": "Эффект VHS",
        "god-rays": "Лучи света (God Rays)",
        "chromatic-aberration": "Хроматическая аберрация",
        "lens-flare": "Блик объектива (Lens Flare)",
        "particles": "Частицы (Particles, Пыль, Искры)",
        "time-lapse": "Таймлапс (Time-Lapse)",
        "slow-motion": "Замедленная съемка (Slow Motion)",
        "bullet-time": "Эффект 'Матрицы' (Bullet Time)",
        "stop-motion": "Стоп-моушн (Stop Motion)",
        "tilt-shift": "Тилт-шифт (Tilt-Shift)",
        "motion-blur": "Размытие движения (Motion Blur)",
        "double-exposure": "Двойная экспозиция",
        "anamorphic-flare": "Анаморфный блик",
        "rain": "Дождь (Rain)",
        "snow": "Снег (Snow)",
        "fire": "Огонь (Fire)",
        "water-splash": "Брызги воды (Water Splash)",
        "electric-sparks": "Электрические искры",
        "hologram": "Голограмма (Hologram)",
        "neon-lines": "Неоновые линии (Neon Lines)",
        "scanlines": "Сканлайны (Scanlines)",
        "pixelation": "Пикселизация",
        "distortion": "Искажение (Distortion)",
        "vignette": "Виньетка (Vignette)",
        "color-grading": "Цветокоррекция (Specific Color Grade)",
        "noise": "Шум (Noise)",
        "bloom": "Свечение (Bloom)"
    },
    "photo-animation": {
        "none": "Без анимации",
        "parallax-zoom": "Параллакс с зумом (Parallax Zoom Effect)",
        "ken-burns": "Эффект Кена Бернса (Ken Burns Effect - Slow Pan & Zoom)",
        "cinemagraph": "Синемаграф (Cinemagraph - Partial Motion)",
        "morph-transition": "Морфинг переход (Morphing Transition)",
        "3d-rotation": "Трехмерное вращение (3D Rotation)",
        "depth-parallax": "Глубинный параллакс (Depth-Based Parallax)",
        "camera-push-in": "Наезд камеры (Camera Push In)",
        "camera-pull-out": "Отъезд камеры (Camera Pull Out)",
        "dolly-zoom": "Долли-зум (Dolly Zoom / Vertigo Effect)",
        "slow-pan-left": "Медленный пан влево (Slow Pan Left)",
        "slow-pan-right": "Медленный пан вправо (Slow Pan Right)",
        "slow-tilt-up": "Медленный наклон вверх (Slow Tilt Up)",
        "slow-tilt-down": "Медленный наклон вниз (Slow Tilt Down)",
        "orbit-rotation": "Орбитальное вращение (Orbit Rotation)",
        "reveal-wipe": "Проявление с вытиранием (Reveal Wipe)",
        "glitch-transition": "Глитч-переход (Glitch Transition)",
        "pixel-sort": "Пиксельная сортировка (Pixel Sort Animation)",
        "datamosh": "Датамош (Datamosh Effect)",
        "chromatic-split": "Хроматическое разделение (Chromatic Split)",
        "liquid-morph": "Жидкостный морфинг (Liquid Morph)",
        "particle-dispersion": "Рассеивание частиц (Particle Dispersion)",
        "freeze-frame-highlight": "Стоп-кадр с подсветкой (Freeze Frame Highlight)",
        "time-slice": "Временной срез (Time Slice / Bullet Time)",
        "seamless-loop": "Бесшовный луп (Seamless Loop)",
        "boomerang": "Бумеранг (Boomerang - Forward & Reverse)",
        "speed-ramp": "Изменение скорости (Speed Ramp)",
        "hyper-lapse": "Гиперлапс (Hyper-Lapse)",
        "stop-motion-style": "Стиль стоп-мошн (Stop Motion Style)",
        "2.5d-parallax": "2.5D параллакс (2.5D Parallax)",
        "depth-of-field-shift": "Смещение глубины резкости (Depth of Field Shift)",
        "animated-painting": "Анимированная живопись (Animated Painting Effect)"
    },
    background: {
        "urban-city": "Городской пейзаж (Urban City)",
        "nature-forest": "Лес (Forest)",
        "cyberpunk-street": "Киберпанк улица (Neon, Rain)",
        "abstract-geometric": "Абстрактный/Геометрический",
        "beach-ocean": "Пляж/Океан",
        "mountain-range": "Горный хребет",
        "desert": "Пустыня (Desert)",
        "space": "Космос (Space, Stars)",
        "historical-castle": "Исторический замок",
        "ancient-ruins": "Древние руины",
        "laboratory": "Секретная лаборатория",
        "medieval-village": "Средневековая деревня",
        "post-apocalyptic-wasteland": "Постапокалиптическая пустошь",
        "floating-island": "Парящий остров (Фэнтези)",
        "volcano": "Активный вулкан",
        "train-station": "Старый вокзал",
        "abandoned-factory": "Заброшенный завод",
        "rooftop-city": "Крыша небоскреба (Ночь)",
        "japanese-garden": "Японский сад",
        "wild-west": "Дикий Запад",
        "deep-sea-trench": "Глубоководный желоб",
        "alien-planet": "Чужая планета",
        "library": "Старинная библиотека",
        "hospital-corridor": "Больничный коридор",
        "concert-stage": "Концертная сцена",
        "classroom": "Школьный класс",
        "art-gallery": "Художественная галерея",
        "suburban-street": "Пригородная улица",
        "futuristic-city": "Футуристический город",
        "underground-bunker": "Подземный бункер",
        "swamp": "Болото",
        "canyon": "Каньон",
        "ice-cave": "Ледяная пещера",
        "space-station": "Космическая станция",
        "pirate-ship": "Пиратский корабль",
        "fairytale-forest": "Сказочный лес",
        "olympic-stadium": "Олимпийский стадион",
        "deserted-highway": "Заброшенное шоссе",
        "rainy-alley": "Дождливый переулок"
    },
    audio: {
        "none": "Без звука",
        "epic-music": "Эпичная оркестровая музыка",
        "synthwave-music": "Синтвейв/Ретро музыка",
        "lo-fi-music": "Lo-fi/Спокойная музыка",
        "nature-sounds": "Звуки природы (ветер, дождь)",
        "voiceover": "Голос за кадром (Voiceover)",
        "sound-effects": "Звуковые эффекты (взрывы, шаги)",
        "ambient": "Атмосферный эмбиент",
        "rock": "Энергичный рок/метал",
        "jazz": "Джаз (Саксофон, Ночной клуб)",
        "classical": "Классическая музыка (Фортепиано, Струнные)",
        "hip-hop": "Хип-хоп (Бит, Бас)",
        "electronic-trance": "Электронная музыка (Транс, Драйв)",
        "horror-score": "Хоррор-саундтрек (Дисонанс)",
        "cinematic-boom": "Кинематографический БУМ (Низкий бас)",
        "footsteps": "Звук шагов",
        "rain-on-window": "Звук дождя по окну",
        "wind-howling": "Вой ветра",
        "crowd-chatter": "Шум толпы/Базар",
        "silence": "Полная тишина",
        "8bit-music": "8-битная музыка (Ретро-игры)",
        "vocal-trance": "Вокальный транс",
        "orchestral-strings": "Оркестровые струнные (Драматические)",
        "acoustic-guitar": "Акустическая гитара (Мягкая)",
        "heavy-metal": "Тяжелый металл (Гитары, Барабаны)",
        "symphony": "Симфонический оркестр",
        "synth-pop": "Синт-поп (80-е)",
        "techno": "Техно (Ритмичный бит)",
        "whispers": "Шепот",
        "explosions": "Звук взрывов",
        "car-engine": "Рев двигателя",
        "birds-chirping": "Пение птиц",
        "ocean-waves": "Шум океанских волн",
        "dubstep": "Дабстеп (Wobble Bass)",
        "folk": "Фолк (Банжо, Скрипка)",
        "gospel": "Госпел (Хор, Орган)",
        "reggae": "Регги (Офф-бит)",
        "opera": "Оперный вокал",
        "medieval-lute": "Средневековая лютня",
        "sci-fi-bleeps": "Научно-фантастические звуки",
        "western-whistle": "Свист в стиле Вестерн",
        "trap-beat": "Трэп-бит (Хай-хэты)",
        "k-pop": "К-поп (Синтезаторы, Вокал)",
        "japanese-flute": "Японская флейта (Шакухати)",
        "sitar": "Ситар (Индийская музыка)"
    },
    "anime-studio": {
        "": "-- Не выбрано --",
        "Studio Ghibli": "Студия Ghibli (Миядзаки)",
        "Makoto Shinkai": "Макото Синкай (Гиперреализм)",
        "Kyoto Animation": "Kyoto Animation (KyoAni)",
        "MAPPA": "MAPPA (Динамика, Жесткий стиль)",
        "Ufotable": "Ufotable (Эффекты, CGI)",
        "Production I.G": "Production I.G (Sci-Fi)",
        "Osamu Tezuka": "Осаму Тэдзука (Классика)",
        "Satoshi Kon": "Сатоси Кон (Сюрреализм)",
        "Katsuhiro Otomo": "Кацухиро Отомо (Акира)",
        "Science SARU": "Science SARU (Экспериментальный)",
        "Toei Animation": "Toei Animation (Длинные сериалы)",
        "Gainax": "Gainax (Эмоциональность)",
        "Trigger": "Trigger (Экшн, Динамика)",
        "Bones": "Bones (Экшн)",
        "Madhouse": "Madhouse (Разнообразие жанров)",
        "Tatsunoko Production": "Tatsunoko Production (Ретро)",
        "Sunrise": "Sunrise (Меха, Гандам)",
        "Pierrot": "Pierrot (Наруто, Блич)",
        "A-1 Pictures": "A-1 Pictures (Sword Art Online)",
        "Wit Studio": "Wit Studio (Атака Титанов)",
        "CloverWorks": "CloverWorks (Spy x Family)",
        "David Production": "David Production (JoJo)",
        "TMS Entertainment": "TMS Entertainment (Детектив Конан)",
        "P.A. Works": "P.A. Works (Красивые фоны)",
        "Shaft": "Shaft (Стиль 'Моногатари')",
        "CoMix Wave Films": "CoMix Wave Films (Синкай)",
        "Studio 4°C": "Studio 4°C (Экспериментальное)",
        "Khara": "Khara (Евангелион)",
        "Orange": "Orange (3D CGI)",
        "J.C.Staff": "J.C.Staff (Toradora, Food Wars)",
        "Doga Kobo": "Doga Kobo (Slice of Life)",
        "White Fox": "White Fox (Re:Zero, Steins;Gate)",
        "Kinema Citrus": "Kinema Citrus (Made in Abyss)",
        "Lerche": "Lerche (Assassination Classroom)",
        "Brain's Base": "Brain's Base (Durarara!!)",
        "Manglobe": "Manglobe (Samurai Champloo)",
        "Gonzo": "Gonzo (Hellsing, Afro Samurai)",
        "AIC": "AIC (Tenchi Muyo!)",
        "Artland": "Artland (Mushishi)",
        "Bee Train": "Bee Train (.hack//SIGN)",
        "Brains Base": "Brains Base (Natsume's Book)",
        "C2C": "C2C (Harukana Receive)",
        "Deen": "Deen (Fate/stay night)",
        "Diomedéa": "Diomedéa (Squid Girl)",
        "EMT Squared": "EMT Squared (Astra Lost in Space)",
        "Encourage Films": "Encourage Films (Kemono Friends)",
        "Feel": "Feel (Oregairu S3)",
        "Gallop": "Gallop (Yu-Gi-Oh!)",
        "GoHands": "GoHands (K Project)",
        "Graphinica": "Graphinica (Hellsing Ultimate)",
        "Hal Film Maker": "Hal Film Maker (Aria)",
        "Hoods Entertainment": "Hoods Entertainment (Magi)",
        "LIDENFILMS": "LIDENFILMS (Tokyo Revengers)",
        "Liden Films": "Liden Films (Berserk 2016)",
        "Millepensee": "Millepensee (Teekyuu)",
        "Nexus": "Nexus (Chivalry of a Failed Knight)",
        "Nippon Animation": "Nippon Animation (World Masterpiece)",
        "Nomad": "Nomad (Rozen Maiden)",
        "OLM": "OLM (Pokémon)",
        "Passione": "Passione (Citrus)",
        "Pine Jam": "Pine Jam (Gamers!)",
        "Project No.9": "Project No.9 (Ro-Kyu-Bu!)",
        "Satelight": "Satelight (Macross Frontier)",
        "Seven": "Seven (Nanana's Buried Treasure)",
        "Seven Arcs": "Seven Arcs (Magical Girl Lyrical Nanoha)",
        "Silver Link": "Silver Link (Non Non Biyori)",
        "Studio Bind": "Studio Bind (Mushoku Tensei)",
        "Studio Chizu": "Studio Chizu (Wolf Children)",
        "Studio Colorido": "Studio Colorido (Penguin Highway)",
        "Studio Deen": "Studio Deen (Konosuba)",
        "Studio Kai": "Studio Kai (Super Cub)",
        "Studio Pierrot": "Studio Pierrot (Tokyo Ghoul)",
        "Studio Ponoc": "Studio Ponoc (Mary and the Witch's Flower)",
        "Tatsunoko": "Tatsunoko (Speed Racer)",
        "Telecom Animation Film": "Telecom Animation Film (Lupin III)",
        "TNK": "TNK (High School DxD)",
        "Triangle Staff": "Triangle Staff (Macross)",
        "Troyca": "Troyca (Aldnoah.Zero)",
        "Xebec": "Xebec (Space Battleship Yamato)",
        "Zexcs": "Zexcs (Umineko)",
        "8bit": "8bit (That Time I Got Reincarnated)",
        "Actas": "Actas (Girls und Panzer)",
        "Arms": "Arms (Elfen Lied)",
        "Asread": "Asread (Mirai Nikki)",
        "Bandai Namco Pictures": "Bandai Namco Pictures (Love Live!)",
        "Bibury Animation Studios": "Bibury Animation Studios (Azur Lane)",
        "Bridge": "Bridge (Fairy Tail)",
        "C-Station": "C-Station (Encouragement of Climb)",
        "Children's Playground Entertainment": "Children's Playground (Arifureta)",
        "Creators in Pack": "Creators in Pack (Yuru Camp)",
        "Eiken": "Eiken (Sazae-san)",
        "Engi": "Engi (Uzaki-chan)",
        "Felix Film": "Felix Film (Heidi)",
        "Geek Toys": "Geek Toys (Plunderer)",
        "Geno Studio": "Geno Studio (Golden Kamuy)",
        "Lay-duce": "Lay-duce (Classroom of the Elite)",
        "MAHO FILM": "MAHO FILM (Isekai Cheat Magician)",
        "Marvy Jack": "Marvy Jack (Keijo!!!!!!!!)",
        "NAZ": "NAZ (Hajimete no Gal)",
        "Nut": "Nut (Saga of Tanya the Evil)",
        "Polygon Pictures": "Polygon Pictures (Knights of Sidonia)",
        "Quad": "Quad (Domestic Girlfriend)",
        "Sanzigen": "Sanzigen (BanG Dream!)",
        "Tezuka Productions": "Tezuka Productions (Black Jack)",
        "Typhoon Graphics": "Typhoon Graphics (Aggressive Retsuko)",
        "Yostar Pictures": "Yostar Pictures (Arknights)"
    },
    "anime-style": {
        "": "-- Не выбрано --",
        "Manga Style": "Стиль Манги (Ч/Б, Штриховка)",
        "Cel Shading": "Сел-шейдинг (Плоские тени)",
        "Digital Painting": "Цифровая живопись (Мягкие переходы)",
        "Traditional Hand-Drawn": "Традиционная ручная рисовка",
        "Chibi/SD": "Чиби/SD (Милый)",
        "Mecha/Gundam": "Меха/Гандам (Техника)",
        "Moé": "Моэ (Милый, Нежный)",
        "Retro 90s Anime": "Ретро Аниме 90-х (Зерно)",
        "Ukiyo-e": "Укиё-э (Японская гравюра)",
        "Shoujo Manga": "Стиль Сёдзё Манги (Цветы, Блеск)",
        "Shonen Manga": "Стиль Сёнэн Манги (Экшн, Динамика)",
        "Gekiga": "Гэкига (Драматический, Взрослый)",
        "Ink Wash": "Тушь (Суми-э)",
        "Watercolor Backgrounds": "Акварельные фоны",
        "Line Art": "Чистый лайн-арт",
        "Thick Lines": "Толстые контуры (Стиль Mob Psycho)",
        "Thin Lines": "Тонкие контуры (Стиль KyoAni)",
        "Minimalist": "Минималистичный",
        "High Contrast": "Высокий контраст (Стиль JoJo)",
        "Pastel Colors": "Пастельные цвета",
        "Vibrant Colors": "Яркие, насыщенные цвета",
        "Monochromatic": "Монохромный",
        "Screentone": "Скринтон (Традиционная манга)",
        "Hatching": "Штриховка (Hatching)",
        "Cross-hatching": "Перекрестная штриховка",
        "Stippling": "Пуантилизм (Stippling)",
        "Gradient Shading": "Градиентные тени",
        "Flat Colors": "Плоские цвета",
        "Soft Shading": "Мягкие тени",
        "Hard Shadows": "Жесткие тени",
        "Rim Lighting": "Контурное освещение",
        "Glow Effects": "Эффекты свечения",
        "Sparkles": "Блестки и искры",
        "Speed Lines": "Линии скорости",
        "Action Lines": "Линии действия",
        "Focus Lines": "Линии фокуса",
        "Halftone": "Полутон (Halftone)",
        "Duotone": "Дуотон (Двухцветный)",
        "Tritone": "Тритон (Трехцветный)",
        "Neon Colors": "Неоновые цвета",
        "Muted Colors": "Приглушенные цвета",
        "Earth Tones": "Земляные тона",
        "Cool Tones": "Холодные тона",
        "Warm Tones": "Теплые тона",
        "Desaturated": "Ненасыщенные цвета",
        "Oversaturated": "Пересыщенные цвета",
        "Noir Style": "Стиль нуар (Черно-белый)",
        "Silhouette": "Силуэты",
        "Outline Heavy": "Толстые контуры",
        "No Outlines": "Без контуров",
        "Colored Outlines": "Цветные контуры",
        "Sketch Style": "Стиль скетча",
        "Rough Sketch": "Грубый скетч",
        "Clean Linework": "Чистый лайнворк",
        "Loose Linework": "Свободный лайнворк",
        "Detailed Linework": "Детализированный лайнворк",
        "Simplified": "Упрощенный стиль",
        "Realistic Proportions": "Реалистичные пропорции",
        "Exaggerated Proportions": "Преувеличенные пропорции",
        "Large Eyes": "Большие глаза",
        "Small Eyes": "Маленькие глаза",
        "Detailed Eyes": "Детализированные глаза",
        "Sparkly Eyes": "Блестящие глаза",
        "Dead Fish Eyes": "Безжизненные глаза",
        "Sharp Features": "Острые черты",
        "Soft Features": "Мягкие черты",
        "Bishonen": "Бисёнэн (Красивый юноша)",
        "Bishojo": "Бисёдзё (Красивая девушка)",
        "Muscular": "Мускулистый стиль",
        "Slender": "Стройный стиль",
        "Cute/Kawaii": "Милый/Кавайный",
        "Gothic": "Готический стиль",
        "Steampunk": "Стимпанк",
        "Cyberpunk Anime": "Киберпанк аниме",
        "Fantasy Anime": "Фэнтези аниме",
        "Sci-Fi Anime": "Научная фантастика",
        "Horror Anime": "Хоррор аниме",
        "Psychological": "Психологический стиль",
        "Surreal": "Сюрреалистичный",
        "Abstract": "Абстрактный",
        "Geometric": "Геометрический",
        "Organic": "Органический",
        "Mechanical": "Механический",
        "Painterly": "Живописный",
        "Photorealistic": "Фотореалистичный",
        "Stylized": "Стилизованный",
        "Retro 80s": "Ретро 80-х",
        "Retro 70s": "Ретро 70-х",
        "Modern Digital": "Современный цифровой",
        "Hand-painted": "Ручная роспись",
        "Airbrush": "Аэрограф",
        "Charcoal": "Уголь",
        "Pencil": "Карандаш",
        "Pen and Ink": "Перо и чернила",
        "Marker": "Маркер",
        "Crayon": "Мелки",
        "Oil Paint": "Масляная краска",
        "Acrylic Paint": "Акриловая краска",
        "Gouache": "Гуашь"
    },
    "anime-artist": {
        "": "-- Не выбрано --",
        "Hayao Miyazaki": "Хаяо Миядзаки",
        "Makoto Shinkai": "Макото Синкай",
        "Satoshi Kon": "Сатоси Кон",
        "Katsuhiro Otomo": "Кацухиро Отомо",
        "Osamu Tezuka": "Осаму Тэдзука",
        "Mamoru Hosoda": "Мамору Хосода",
        "Isao Takahata": "Исао Такахата",
        "Hideaki Anno": "Хидэаки Анно",
        "Masaaki Yuasa": "Масааки Юаса",
        "Shinichiro Watanabe": "Синитиро Ватанабэ",
        "Yoshiaki Kawajiri": "Йосиаки Кавадзири",
        "Rintaro": "Ринтаро",
        "Yoshiyuki Tomino": "Йосиюки Томино",
        "Kunihiko Ikuhara": "Кунихико Икухара",
        "Tensai Okamura": "Тэнсай Окамура",
        "Akiyuki Shinbo": "Акиюки Синбо",
        "Naoko Yamada": "Наоко Ямада",
        "Hiroyuki Imaishi": "Хироюки Имаиси",
        "Tetsuro Araki": "Тэцуро Араки",
        "Eiichiro Oda": "Эйитиро Ода (One Piece)",
        "Masashi Kishimoto": "Масаси Кисимото (Naruto)",
        "Akira Toriyama": "Акира Торияма (Dragon Ball)",
        "Hajime Isayama": "Хадзимэ Исаяма (Attack on Titan)",
        "Kentaro Miura": "Кэнтаро Миура (Berserk)",
        "Yoshihiro Togashi": "Йосихиро Тогаси (Hunter x Hunter)",
        "Naoki Urasawa": "Наоки Урасава (Monster)",
        "Takehiko Inoue": "Такэхико Иноуэ (Slam Dunk)",
        "Hirohiko Araki": "Хирохико Араки (JoJo's Bizarre Adventure)",
        "Tsugumi Ohba": "Цугуми Оба (Death Note)",
        "Takeshi Obata": "Такэси Обата (Death Note, Bakuman)",
        "CLAMP": "CLAMP (Cardcaptor Sakura)",
        "Rumiko Takahashi": "Румико Такахаси (Inuyasha)",
        "Junji Ito": "Дзюндзи Ито (Horror)",
        "Sui Ishida": "Суй Исида (Tokyo Ghoul)",
        "Tite Kubo": "Тайто Кубо (Bleach)",
        "Hiro Mashima": "Хиро Масима (Fairy Tail)",
        "Kohei Horikoshi": "Кохэй Хорикоси (My Hero Academia)",
        "Koyoharu Gotouge": "Коёхару Готоугэ (Demon Slayer)",
        "Gege Akutami": "Гэгэ Акутами (Jujutsu Kaisen)",
        "Tatsuki Fujimoto": "Тацуки Фудзимото (Chainsaw Man)",
        "ONE": "ONE (One Punch Man, Mob Psycho)",
        "Yusuke Murata": "Юсукэ Мурата (One Punch Man)",
        "Katsura Hoshino": "Кацура Хосино (D.Gray-man)",
        "Yoshiki Tanaka": "Йосики Танака (Legend of Galactic Heroes)",
        "Katsura Masakazu": "Кацура Масакадзу (Video Girl Ai)",
        "Masamune Shirow": "Масамунэ Сироу (Ghost in the Shell)",
        "Yoshitoshi ABe": "Йоситоси АБе (Lain, Haibane Renmei)",
        "Range Murata": "Рэндз Мурата (Last Exile)",
        "Kazuki Takahashi": "Кадзуки Такахаси (Yu-Gi-Oh!)",
        "Nobuhiro Watsuki": "Нобухиро Вацуки (Rurouni Kenshin)",
        "Yasuhiro Nightow": "Ясухиро Найтоу (Trigun)",
        "Kouta Hirano": "Коута Хирано (Hellsing)",
        "Tsutomu Nihei": "Цутому Нихэй (Blame!)",
        "Hiromu Arakawa": "Хирому Аракава (Fullmetal Alchemist)",
        "Yoshiyuki Sadamoto": "Йосиюки Садамото (Evangelion)",
        "Monkey Punch": "Манки Панч (Lupin III)",
        "Go Nagai": "Го Нагай (Devilman)",
        "Leiji Matsumoto": "Лэйдзи Мацумото (Captain Harlock)",
        "Mitsuru Adachi": "Мицуру Адати (Touch)",
        "Kaoru Mori": "Каору Мори (Emma)",
        "Ai Yazawa": "Ай Язава (Nana)",
        "Natsuki Takaya": "Нацуки Такая (Fruits Basket)",
        "Arina Tanemura": "Арина Танэмура (Full Moon)",
        "Yuu Watase": "Юу Ватасэ (Fushigi Yuugi)",
        "Kaori Yuki": "Каори Юки (Angel Sanctuary)",
        "Matsuri Hino": "Мацури Хино (Vampire Knight)",
        "Bisco Hatori": "Биско Хатори (Ouran High School)",
        "Mitsuba Takanashi": "Мицуба Таканаси (Crimson Hero)",
        "Katsuhisa Kigitsu": "Кацухиса Кигицу",
        "Yuki Midorikawa": "Юки Мидорикава (Natsume's Book)",
        "Kazue Kato": "Кадзуэ Като (Blue Exorcist)",
        "Shinobu Ohtaka": "Синобу Отака (Magi)",
        "Adachitoka": "Адатитока (Noragami)",
        "Kafka Asagiri": "Кафка Асагири (Bungo Stray Dogs)",
        "Sango Harukawa": "Санго Харукава (Bungo Stray Dogs)",
        "Haruichi Furudate": "Харуити Фурудатэ (Haikyuu!!)",
        "Tadatoshi Fujimaki": "Тадатоси Фудзимаки (Kuroko's Basketball)",
        "Yuto Tsukuda": "Юто Цукуда (Food Wars!)",
        "Shun Saeki": "Сун Саэки (Food Wars!)",
        "Reki Kawahara": "Рэки Кавахара (Sword Art Online)",
        "abec": "abec (Sword Art Online)"
    }
};
